name = "PortableGameNotation"
uuid = "741eb8d8-1b8a-5b1d-9526-a7052a967f3d"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test"]
